apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null    
  labels:
    app: mynginx1
  name: mynginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginx1        
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}        
status: {}