FROM node:16-alpine

WORKDIR "/app"
# RUN mkdir /app/node_modules

# RUN mkdir /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
COPY package.json .
RUN npm install 
# RUN chown -R node:node /app/node_modules

# COPY . . 

CMD ["npm","run","start"]
